# Pré-processamento de Dados

Técnicas de preparação de dados antes do treinamento de modelos.

**Conceitos:**
- Imputação de valores ausentes (`SimpleImputer`, `KNNImputer`)
- Codificação de variáveis categóricas (`OneHotEncoder`, `LabelEncoder`)
- Padronização de features (`StandardScaler`)

# IMPORTS

In [16]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.impute import KNNImputer
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, OneHotEncoder
from sklearn.preprocessing import StandardScaler

# OPERAÇÕES

In [17]:
# Criar um dataset com dados faltantes

dados = {
    'idade': [25, 30, np.nan, 40, 22, 35, np.nan, 45, 28, 50],
    'salario': [5000, 6000, 5500, np.nan, 4500, 7000, 6200, 8000, 5800, np.nan],
    'cidade': ['SP', 'RJ', 'SP', 'BH', 'RJ', 'SP', 'BH', 'SP', 'RJ', 'SP'],
    'genero': ['M', 'F', 'F', 'M', 'M', 'F', 'F', 'M', 'M', 'F'],
    'comprou': ['Não', 'Sim', 'Não', 'Sim', 'Não',
               'Sim', 'Não', 'Sim', 'Não', 'Sim']
}

df = pd.DataFrame(dados)

# Separar perguntas das respostas
X = df.drop('comprou', axis=1)
y = df[['comprou']]

In [18]:
# Dividir os dados(treino e teste)

X_treino, X_teste, y_treino, y_teste = train_test_split(
    X,
    y,
    train_size=0.2,
    random_state=42
)

X_treino

   idade  salario cidade genero
3   40.0      NaN     BH      M
6    NaN   6200.0     BH      F

In [19]:
imputer_idade = SimpleImputer(strategy='mean')

X_treino['idade'] = imputer_idade.fit_transform(X_treino[['idade']])
X_teste['idade'] = imputer_idade.fit_transform(X_teste[['idade']])

print('Idade tratada no treino')
X_treino['idade'].values

Idade tratada no treino

array([40., 40.])

In [20]:
imputer_knn = KNNImputer(n_neighbors=3)

X_treino['salario'] = imputer_knn.fit_transform(X_treino[['salario']])
X_teste['salario'] = imputer_knn.fit_transform(X_teste[['salario']])

print('Salario tratado no treino')
X_treino['salario'].values

Salario tratado no treino

array([6200., 6200.])

In [26]:
le = LabelEncoder()

y_treino_label = le.fit_transform(y_treino)
y_teste_label = le.transform(y_teste)

print(f'Resposta transformada: {y_treino_label}')

Resposta transformada: [1 0]

C:\Users\Júlio César\AppData\Roaming\Python\Python313\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Júlio César\AppData\Roaming\Python\Python313\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

In [22]:
ohe = OneHotEncoder(
    sparse_output=False,  # ver o array numpy visualmente
    handle_unknown='ignore'  # se esxistir uma categorias desconhecida retorna 0
)

# Regra de ouro
X_treino_cat = ohe.fit_transform(X_treino[['cidade', 'genero']])
X_teste_cat = ohe.transform(X_teste[['cidade', 'genero']])

# Converter em um DF para melhor visualização
colunas_novas = ohe.get_feature_names_out(['cidade', 'genero'])
df_cat_treino = pd.DataFrame(X_treino_cat, columns=colunas_novas, index=X_treino.index)
df_cat_teste = pd.DataFrame(X_teste, columns=colunas_novas, index=X_teste.index)

df_cat_treino

   cidade_BH  genero_F  genero_M
3        1.0       0.0       1.0
6        1.0       1.0       0.0

In [23]:
# colocar os dados codificados nos dados de treino e teste
X_treino = pd.concat([X_treino.drop(columns=['cidade', 'genero']),
                      df_cat_treino], axis=1)
X_teste = pd.concat([X_teste.drop(columns=['cidade', 'genero']),
                      df_cat_teste], axis=1)

X_treino.head()

   idade  salario  cidade_BH  genero_F  genero_M
3   40.0   6200.0        1.0       0.0       1.0
6   40.0   6200.0        1.0       1.0       0.0

In [24]:
scaler = StandardScaler()

# Escalar somente as colunas numéricas originais
cols_num = ['idade', 'salario']

X_treino[cols_num] = scaler.fit_transform(X_treino[cols_num])
X_teste[cols_num] = scaler.transform(X_teste[cols_num])

X_treino

   idade  salario  cidade_BH  genero_F  genero_M
3    0.0      0.0        1.0       0.0       1.0
6    0.0      0.0        1.0       1.0       0.0